Human-Computer Interaction prototype/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from .settings import *
from CourseApp.views import *

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('register/', register, name='register'),
                  path('login/', login, name='login'),
                  path('', index, name='index'),
                  path('lectures/', lectures, name='lectures'),
                  path('video/', video, name='video'),
                  path('tests/', tests, name='tests'),
                  path('test/', test, name='test'),
                  path('logout/', logout, name='logout'),
    path('forum/', forum, name='forum')
              ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

CourseApp/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models


# from django.forms import forms


class Learner(models.Model):
    user_name = models.CharField(null=False, blank=False, max_length=50)
    first_name = models.CharField(null=False, blank=False, max_length=50)
    last_name = models.CharField(null=False, blank=False, max_length=50)
    email = models.EmailField(null=False, blank=False, max_length=40, primary_key=True)
    password = models.CharField(max_length=32, blank=False, null=False)

    birth_date = models.DateField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # image = models.ImageField(upload_to="student_images/")
    is_registered = models.BooleanField(default=False)
    is_logged_in = models.BooleanField(default=False)

    def __str__(self):
        return f"Name: {self.first_name} Surname: {self.last_name}"

    def welcome(self):
        return f"{self.first_name} {self.last_name}"


class Instructor(models.Model):
    user_name = models.CharField(null=False, max_length=50)
    first_name = models.CharField(null=False, max_length=50)
    last_name = models.CharField(null=False, max_length=50)
    email = models.EmailField(null=False, max_length=40)
    #  image = models.ImageField(upload_to="instructor_images/")
    birth_date = models.DateField()
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    BACHELOR = 'Bachelor'
    MASTER = 'Master'
    DOCTORATE = 'Doctorate'
    DEGREES = [
        (BACHELOR, 'Bachelor'), (MASTER, 'Master'), (DOCTORATE, 'Doctorate'),
    ]
    degree = models.CharField(choices=DEGREES, default=BACHELOR, max_length=50)

    def __str__(self):
        return f" {self.first_name} {self.last_name} {self.degree}"


class Course(models.Model):
    name = models.CharField(null=False, max_length=50)
    description = models.TextField(max_length=1000, default="")
    image = models.FileField(upload_to="course_images/", blank=True, null=True)
    instructors = models.ManyToManyField(Instructor)
    users = models.ManyToManyField(User, through='Enrollment')
    selected = models.BooleanField(default=False)

    def shortened_description(self):
        return self.description[:300] + "..."

    def __str__(self):
        return f"{self.name}"

    def instructors_string(self):
        str_repr_of_ins = [instr.__str__() for instr in self.instructors.all()]
        print(str_repr_of_ins)
        return ", ".join(str_repr_of_ins)

    def grade(self):
        total = 0
        lessons = Lesson.objects.filter(course__name=self.name).all()
        for lesson in lessons:
            if lesson.grade == 0:
                return 5
            total += lesson.grade

        return int(total / lessons.__len__())


class Lesson(models.Model):
    title = models.CharField(max_length=50)
    order_no = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    content = models.TextField(max_length=10000)
    video = models.FileField(upload_to='videos/', default="", null=True, blank=True)
    link = models.URLField(max_length=3000, null=True, blank=True)
    selected = models.BooleanField(default=False)
    grade = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.title}, {self.course.__str__()}"


class Enrollment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    date_of_enrollment = models.DateField()


class Question(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    course = models.ManyToManyField(Course)
    question_content = models.TextField(max_length=10000, null=True, blank=True, default="")
    question_content_image = models.FileField(upload_to='question_images/', null=True, blank=True, default="")
    grade = models.IntegerField(default=0)

    def __str__(self):
        return f"Content: {self.question_content} Lesson: {self.lesson.__str__()} Grade: {self.grade}"


class Choice(models.Model):
    choice_text = models.CharField(max_length=500)
    is_correct = models.BooleanField()
    question = models.ManyToManyField(Question)

    def __str__(self):
        return f"Content: {self.choice_text} Question: {self.question.all()}"


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_published = models.DateTimeField()
    text = models.TextField(max_length=10000, default="")
    files = models.FileField(upload_to='student_images/', blank=True, default="")

    def __str__(self):
        return f"{self.author} {self.date_published} {self.text}"


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_published = models.DateTimeField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField(max_length=10000, default="")
    files = models.FileField(upload_to='student_images/', blank=True, default="")

    def __str__(self):
        return f"{self.author} {self.date_published} {self.post}"

templates/dependencies.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dependencies</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'lectures' %}">Lectures</a>
            <a class="nav-item nav-link" href="{% url 'tests' %}">Tests</a>
            <a class="nav-item nav-link" href="#">Forum</a>

            <a class="nav-item nav-link" href="#">Logout</a>
        </div>
    </div>
</nav>
</body>
</html>

templates/forum.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Forum</title>
</head>
<body>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'lectures' %}">Lectures</a>
            <a class="nav-item nav-link" href="{% url 'tests' %}">Tests</a>
            <a class="nav-item nav-link active" href="{% url 'forum' %}">Forum</a>

            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
</nav>
<section style="background-color: #eee;">
<div class="container my-5 py-5">

    <form enctype="multipart/form-data" method="post">
           {% csrf_token %}
    {{ post_form.as_p }}

     <div class="button">
                                        <button type="submit" class="btn btn-primary">Post</button>
                                    </div>
          </form>
</div>

    {% for post, comments in query_dict.items %}
        <div class="container my-5 py-5">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12 col-lg-10 col-xl-8">
                    <div class="card">
                        <div class="card-body">
                            <div class="d-flex flex-start align-items-center">
                                <div>
                                    <h6 class="fw-bold text-primary mb-1">{{ post.author }}</h6>
                                    <p class="text-muted small mb-0">
                                        {{ post.date_published }}
                                    </p>
                                </div>
                            </div>

                            <p class="mt-3 mb-4 pb-2">
                                {{ post.text }}
                            </p>
                        </div>

                        <div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
                            <div class="d-flex flex-start w-100">
                                <div class="form-outline w-100">
                                    {% for comment in comments %}
                                        <h6 class="fw-bold text-primary mb-1">{{ comment.author }}</h6>
                                        <p class="text-muted small mb-0">
                                            {{ comment.date_published }}

                                        </p>
                                        <textarea class="form-control" id="textAreaExample" rows="4"
                                                  style="background: #fff;" disabled>{{ comment.content }}</textarea>
    {% endfor %}
                                        </div>

                            </div>

                            <div class="mb-5">

                                <form method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ comment_form.as_p }}
                                    {% with comment_form.post as post %}
                                        {{ comment_form.save }}

                                    {% endwith %}
                                    <select name="post"  class="form-control" required="" id="id_post">
<option value="{{ post }}" selected>{{ post.text }}</option>

</select>
                                    <div class="button">
                                        <button type="submit" class="btn btn-primary">Post</button>
                                    </div>
                                </form>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</section>
</body>
</html>
<style>
#id_post
{
    visibility: hidden;
}
body
{
    background-color: #eeeeee;
}
</style>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    {% if learner.is_registered and learner.is_logged_in %}
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'lectures' %}">Lectures</a>
            <a class="nav-item nav-link" href="{% url 'tests' %}">Tests</a>
            <a class="nav-item nav-link" href="{% url 'forum' %}">Forum</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">Log out</a>
        </div>
    </div>
    {% else %}
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href={% url 'login' %}>Log in</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        </div>
    </div>
    {% endif %}
</nav>
<div class="container justify-content center mt-5 text-center mb-5">
        <div class="row">
        {% if learner.is_logged_in %}
        <h1 class="welcome text-white" id="welcomeH1">Welcome, {{ learner.welcome }}.</h1>

        {% else %}
        <h1 class="welcome text-white" id="welcomeH1">Welcome, Guest.</h1>
      {% endif %}
        <div class="col-12">
        <h3 class="welcome text-white mt-5 mb-5">Select a course you would like to enroll to:</h3>
        <div class="row mb-5 mt-5">
    </div>

        <div class="container">
        <div class="row justify-content-center mb-5">
        {% for course in courses %}
            <div class="card col-3 me-5 mt-5" style="width: 500px">
  <img src="{{ MEDIA_URL}}{{ course.image.url }}" class="card-img-top" alt="{{ course.id }}" style="width: 476px;height: 200px">
  <div class="card-body">
    <h5 class="card-title">{{ course.name }}</h5>
    <p class="card-text"><strong>Instructors: </strong>{{ course.instructors_string }}</p>
      <p class="card-text"><strong>Course description: </strong><br>{{ course.shortened_description }}</p>
     <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
         <input type="text" name="name" maxlength="50" class="form-control" required="" id="id_name"  value="{{ course.name }}">
         {% if learner.is_registered and learner.is_logged_in %}
        <div class="button">
             <button type="submit" class="btn btn-primary" style="bottom: -12px; position: relative;">Enroll now!</button>
        </div>
         {% else %}
          <div class="button">
             <button type="submit" class="btn btn-primary" style="bottom: -12px; position: relative;" disabled>Enroll now!</button>
        </div>
         {% endif %}
    </form>
  </div>
</div>


        {% endfor %}
        </div>
        </div>

            </div>
        </div>
        </div>





</body>
</html>
<style>
    body {
        background-repeat: round;
        background-image: url("https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg");
    }
    label
    {
        color: white;
    }
    .form-control {
        visibility: hidden;
    }
</style>

templates/lectures.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lectures</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link active" href="{% url 'lectures' %}">Lectures</a>
            <a class="nav-item nav-link" href="{% url 'tests' %}">Tests</a>
            <a class="nav-item nav-link" href="{% url 'forum' %}">Forum</a>

            <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        </div>
    </div>
</nav>

<div class="row justify-content center text-center mt-5" style="color: whitesmoke">
<h1>{{ lectures.first.course.name }}</h1>
</div>

<div class="container justify-content left mt-5">
    <section class="intro">
        <div class="bg-image h-100"
             style="background-image: url('https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg');">
            <div class="mask d-flex align-items-center h-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12">
                            <div class="card mask-custom">
                                <div class="card-body">

                                    <div class="table-responsive">
                                        <table class="table table-borderless text-white mb-0">
                                            <thead>
                                            <tr>
                                                <th scope="col"># Week</th>
                                                <th scope="col">Title</th>
                                                <th scope="col">Action</th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for lecture in lectures %}
                                                <tr>
                                                    <th scope="row">{{ lecture.order_no }}</th>
                                                    <td>{{ lecture.title }}</td>

{#                                                <td style="width: 120px"><a  class="btn btn-primary" style="width: 120px" href="{% url 'video' %}">Go to lecture</a> </td>#}
                                                <td>
                                                         <div class="col">
                                                 <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
         <input type="text" name="name" maxlength="50" class="form-control" required="" id="id_name"  value="{{ lecture.title }}" style="width: 0; height: 0">
    <div class="button">
         <button type="submit" class="btn btn-primary" style="bottom: 12px; position: relative;">Go to lecture!</button>
    </div>
    </form>
                                                </div>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

</body>
</html>
<style>
    html,
body,
.intro {
  height: 100%;
}

table td,
table th {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
label
{
    color: white;
}
.mask-custom {
  background: rgba(24, 24, 16, .2);
  border-radius: 2em;
  backdrop-filter: blur(25px);
  border: 2px solid rgba(255, 255, 255, 0.05);
  background-clip: padding-box;
  box-shadow: 10px 10px 10px rgba(46, 54, 68, 0.03);
}
body
{
    background-image: url("https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg");
}
.form-control
{
    visibility: hidden;
}
</style>

templates/login.html
<!DOCTYPE html>
<html lang="en">
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link active" href={% url 'login' %}>Log in</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
        </div>
    </div>

</nav>
<div class="container">
<form method="post" enctype="multipart/form-data" class="mt-5">
        {% csrf_token %}
        {{ form.as_p }}
    <div class="button">
         <button type="submit" class="btn btn-primary" style="bottom: -12px; position: relative">Submit</button>
    </div>
    </form>
    </div>
</body>
</html>
<style>
    body
    {
        background-image: url("https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg");
    }
    label
{
    color: white;
}
</style>

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href={% url 'login' %}>Log in</a>
            <a class="nav-item nav-link active" href="{% url 'register' %}">Register</a>
        </div>
    </div>

</nav>
<div class="container">
    <form method="post" enctype="multipart/form-data" class="mt-5">
        {% csrf_token %}
        {{ form.as_p }}
         <div class="button justify-content center">
         <button type="submit" class="btn btn-primary"  style="bottom: -12px; position: relative">Submit</button>
    </div>
    </form>
</div>
</body>
</html>
<style>
    body
    {
        background-image: url("https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg");
    }
    label
{
    color: white;
}
</style>

templates/tests.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lectures</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'lectures' %}">Lectures</a>
            <a class="nav-item nav-link active" href="{% url 'tests' %}">Tests</a>
            <a class="nav-item nav-link" href="{% url 'forum' %}">Forum</a>

            <a class="nav-item nav-link" href="{% url 'logout' %}">Log out</a>
        </div>
    </div>
</nav>
<div class="row justify-content center text-center mt-5 mb-5" style="color: whitesmoke">
<h1>{{ lessons.first.course.name }}</h1>
    <h1>Grade: {{ lessons.first.course.grade }}</h1>
</div>

<div class="container justify-content left">
    <section class="intro">
        <div class="bg-image h-100"
             style="background-image: url('https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg');">
            <div class="mask d-flex align-items-center h-100">
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-12">
                            <div class="card mask-custom">
                                <div class="card-body">
                                    <div class="table-responsive">
                                        <table class="table table-borderless text-white mb-0">
                                            <thead>
                                            <tr>

                                                <th scope="col">Title</th>
                                                <th scope="col">Test your knowledge!</th>
                                                <th scope="col">Grade</th>

                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for lesson in lessons %}
                                                <tr>

                                                    <td>{{ lesson }}</td>
                                                    <td>
                                                         <div class="col">
                                                 <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
         <input type="text" name="name" maxlength="50" class="form-control" required="" id="id_name"  value="{{ lesson.title }}" style="width: 0; height: 0">
    <div class="button">
         <button type="submit" class="btn btn-primary" style="bottom: 12px; position: relative;">Start assignment!</button>
    </div>
    </form>
                                                </div>
                                                    </td>
                                                    {% if lesson.grade == 0 %}
                                                    <td>-</td>
                                                        {% else %}
                                                        <td>{{ lesson.grade }}</td>
                                                {% endif %}

                                                </tr>
                                            {% endfor %}

                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

</body>
</html>
<style>
    html,
body,
.intro {
  height: 100%;
}

table td,
table th {
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}
label
{
    color: white;
}
.mask-custom {
  background: rgba(24, 24, 16, .2);
  border-radius: 2em;
  backdrop-filter: blur(25px);
  border: 2px solid rgba(255, 255, 255, 0.05);
  background-clip: padding-box;
  box-shadow: 10px 10px 10px rgba(46, 54, 68, 0.03);
}
.form-control
{
    visibility: hidden;
}
body
{
    background-image: url("https://financialservicesblog.accenture.com/wp-content/uploads/2020/10/AI_Concept.jpg");
}
</style>

templates/video.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Video</title>
</head>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'index' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'lectures' %}">Lectures</a>
            <a class="nav-item nav-link" href="{% url 'tests' %}">Tests</a>
            <a class="nav-item nav-link" href="#">Forum</a>

            <a class="nav-item nav-link" href="#">Logout</a>
        </div>
    </div>
</nav>
{% if lecture.video != "" %}
<video width='1879' height='800' controls>
        <source src="{{ MEDIA_URL }}{{ lecture.video.url }}" type='video/mp4'>
</video>


{% else %}
<iframe width="1879" height="800" src="{{ lecture.link }}" title="{{ lecture.title }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
{% endif %}
</body>
</html>
<style>
    p
    {
        color: black;
    }
</style>